[package]
name = "hepmc2-macros"
version = "0.1.0"
edition = "2021"
description = "Macros for the hepmc2 crate"
license = "GPL-3.0-or-later"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[features]
tokio = []
sync = []
